# Generated by Django 3.1.2 on 2021-02-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_description',
            new_name='user_desc',
        ),
    ]
