# Generated by Django 3.1.2 on 2021-02-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210228_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_desc',
        ),
        migrations.AddField(
            model_name='user',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
