# Generated by Django 3.1.2 on 2021-02-18 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210213_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(db_column='gender_desc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gender', to_field='gender_desc'),
        ),
    ]
