# Generated by Django 3.1.2 on 2021-02-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210218_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fitness_exp',
            new_name='fitness_exp_title',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='gender_desc',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='workout_intensity',
            new_name='workout_intensity_title',
        ),
    ]
