# Generated by Django 3.1.2 on 2021-03-07 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210228_2129'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('workout_title', models.CharField(max_length=100)),
                ('workout_desc', models.CharField(max_length=1000)),
                ('premium_workout', models.BooleanField()),
                ('workout_picture', models.ImageField(blank=True, null=True, upload_to='workout_pictures')),
                ('workout_creator', models.ForeignKey(db_column='workout_creator_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'workout',
            },
        ),
        migrations.CreateModel(
            name='PlaylistWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('playlist', models.ForeignKey(db_column='playlist_id', on_delete=django.db.models.deletion.CASCADE, to='user_profile.workoutplaylist')),
                ('workout', models.ForeignKey(db_column='workout_id', on_delete=django.db.models.deletion.CASCADE, to='user_profile.workout')),
            ],
            options={
                'db_table': 'playlist_workout',
            },
        ),
    ]
