# Generated by Django 3.1.2 on 2021-02-12 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workoutplaylist',
            table='workout_playlist',
        ),
    ]
