# Generated by Django 3.1.2 on 2021-03-07 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210228_2129'),
        ('user_profile', '0002_playlistworkout_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='gender',
            field=models.ForeignKey(db_column='gender_desc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gender'),
        ),
    ]
