# Generated by Django 3.1.2 on 2021-02-12 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('user_profile', '0002_auto_20210212_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplaylist',
            name='owner_id',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
