# Generated by Django 3.1.2 on 2021-03-07 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_workout_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='gender',
        ),
    ]
