# Generated by Django 3.1.2 on 2021-03-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210228_2129'),
        ('user_profile', '0004_remove_workout_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplaylist',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.ForeignKey(db_column='workout_type_id', on_delete=django.db.models.deletion.CASCADE, to='api.workouttype'),
            preserve_default=False,
        ),
    ]
