# Generated by Django 3.1.2 on 2021-03-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20210307_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplaylist',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
